name: Bugreport
description: "Report a bug related to the Purposeful Storage mod here."
labels: ["status: new"]

body:
  - type: input
    id: gameversion
    attributes:
      label: "Game Version"
      description: "What Vintage Story game version are you using?"
      placeholder: "v1.20.10"
    validations:
      required: false

  - type: input
    id: modversion
    attributes:
      label: "Purposeful Storage Mod Version"
      description: "Which version of the Purposeful Storage mod are you using?"
      placeholder: "v1.1.0"
    validations:
      required: true

  - type: dropdown
    id: onlypurposefulstorage
    attributes:
      label: "Does this issue happen when only Purposeful Storage is enabled (no other mods)?"
      description: "Disable all other mods and test again, if possible."
      options:
        - "Yes"
        - "No"
        - "I don't know"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Explain the issue you're running into."
      placeholder: "What exactly goes wrong? When did it start happening? What are the steps to reproduce?"
    validations:
      required: false
